volumes:
  registry-image-data:
  registry-auth:
  swagger-docs:

networks:
  padoc-network:
    driver: bridge

services:
  proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${BASE_DIR}/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - padoc-network
    restart: unless-stopped

  padoc-backend:
    image: i13a106.p.ssafy.io:5000/padoc_backend
    container_name: padoc-backend
    env_file:
      - ${BASE_DIR}/docker/secure/.env
    networks:
      - padoc-network
    restart: unless-stopped
    profiles:
      - "service-component"

  padoc-voice-analysis:
    image: i13a106.p.ssafy.io:5000/padoc_voice_analysis
    container_name: padoc-voice-analysis
    volumes:
      - ${BASE_DIR}/docker/model/savemodel_101_all_Dense_32.h5:/resource/savemodel_101_all_Dense_32.h5
    env_file:
      - ${BASE_DIR}/docker/secure/.env
    networks:
      - padoc-network
    restart: unless-stopped
    profiles:
      - "service-component"

  padoc-frontend:
    image: i13a106.p.ssafy.io:5000/padoc_frontend
    container_name: padoc-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BE_API_URL=/api
    networks:
      - padoc-network
    restart: unless-stopped
    profiles:
      - "service-component"

  api-docs:
    image: swaggerapi/swagger-ui:latest
    container_name: api-docs
    volumes:
      - ${BASE_DIR}/docs/padoc_api.json:/usr/share/nginx/html/padoc_api.json
    environment:
      - URL=padoc_api.json
    networks:
      - padoc-network
    restart: unless-stopped
    profiles:
      - "dev-util"

  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000" 
    volumes:
      - ${BASE_DIR}:/var/lib/registry
      - ${BASE_DIR}/docker/auth:/auth
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_HTTP_TLS_CERTIFICATE=/etc/letsencrypt/live/i13a106.p.ssafy.io/fullchain.pem
      - REGISTRY_HTTP_TLS_KEY=/etc/letsencrypt/live/i13a106.p.ssafy.io/privkey.pem
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin=['https://i13a106.p.ssafy.io']
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods=['HEAD', 'GET', 'OPTIONS', 'DELETE']
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers=['Authorization', 'Accept']
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials=['true']
    networks:
      - padoc-network
    restart: unless-stopped
    profiles:
      - "dev-util"

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE="My Private Registry"
      - DELETE_IMAGES=true
      - REGISTRY_URL=https://i13a106.p.ssafy.io:5000
    networks:
      - padoc-network
    depends_on:
      - registry
    restart: unless-stopped
    profiles:
      - "dev-util"