import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/atoms/header";
import { ThemeProvider } from "../components/atoms/themeProvider";

export const metadata: Metadata = {
  title: "Padoc : Parkinson's Doctor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Header />
          <main>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
